### ISSUE TITLE
LSTM's temporal behavior

### ISSUE THREAD

**Issue by ricvolpi** [MattiaLitrico/Smart-Fermenter#3]
Hey, thanks for releasing code and data.

I was looking at your training script, and I'm a bit confused by these lines:

https://github.com/MattiaLitrico/Smart-Fermenter/blob/ec8e8a784092e74ce3920d8f794b3532e3b683bb/train.py#L59-L62

Is it expected to always initialize the hidden state before feeding it to the model? Shouldn't we feed it with the previous iteration's, as far as the samples from t and t-1 are from the same fermentation sequence?

Thanks in advance!

**Comment by ricvolpi** [comment]
I mean, in this way the LSTM does behave recurrently within the 20-dimensional sequence in each batch, but I don't understand how the continuous processing described in Figure 5 from [your paper](https://www.mdpi.com/2311-5637/9/6/503) is implemented. Thanks!

<img width="532" alt="image" src="https://github.com/user-attachments/assets/18fa441d-354b-4993-8646-1c90e2d79388">

**Comment by MattiaLitrico** [comment]
Yes you are right! The LSTM behave recurrently within the 20-dimensional sequence in each batch. Since we have sliding windows with overlapping, this approximates the continous processing described in the figure. 

-"Shouldn't we feed it with the previous iteration's, as far as the samples from t and t-1 are from the same fermentation sequence?". Yes, our solution is an approximation of this behaviour.

**Comment by ricvolpi** [comment]
Got it. Thanks!
